### PR TITLE
add paleo hw4 

### PR DESCRIPTION
**Pull request by patrickaleo**

### CODE REVIEW

**Comment by gnarayan** [comment]
As discussed, I'll start assigning a reviewer at random - these need to be reciprocal (i.e. you may not be the person reviewing your reviewer's solution). For this homework set, I've assigned @sihanli3

**Comment by gnarayan** [comment]
@sihanli3 - please look over the homework solution from @patrickaleo and see if you have any questions, or comment on any aspect that differs from your solution.

**Comment by sihanli3** [comment]
Your results look good. In problem 1, the plot looks wonderful and verified that your samples match the target pdf very well.  Parameters are reasonable according to your dataset in problem 3, and MCMC fits data well. 

I like your codes with appropriate comments in lines, which is easy to understand. Also, I noticed that you defined functions or modules instead of writing the expressions line by line. In that case, your codes look well-organized and logical. After reading your solutions, I realized that some parts of my homework should be improved. Thank you so much!

**Review by sihanli3 — COMMENTED** [review]
Your results look good. In problem 1, the plot looks wonderful and verified that your samples match the target pdf very well. Parameters are reasonable according to your dataset in problem 3, and MCMC fits data well.

I like your codes with appropriate comments in lines, which is easy to understand. Also, I noticed that you defined functions or modules instead of writing the expressions line by line. In that case, your codes look well-organized and logical. After reading your solutions, I realized that some parts of my homework should be improved. Thank you so much!

**Pull request merged**
