### PR TITLE
hw4-still working :(

### PR DESCRIPTION
**Pull request by cspatel2**

### CODE REVIEW

**Comment by gnarayan** [comment]
As discussed, I'll start assigning a reviewer at random - these need to be reciprocal (i.e. you may not be the person reviewing your reviewer's solution).  For this homework set, I've assigned @frankfjy - please look over the homework solution from @cspatel2 and see if you have any questions, or comment on any aspect that differs from your solution.

**Comment by frankfjy** [comment]
Hi Charmi,

For problem 1, the coding algorithm seems to be correct, but it would be beneficial to generate more samples (say 10k-100k) to show a smoother distribution. It would also be helpful if you could over plot the target pdf on top of the histogram.

For problem 2, the sampler seems to have a minor bug. Inside the while loop of the function ***metroplis_hastings***, the initial values have been assigned to **x_i** and **y_i** every time, thus the sampler cannot walk in the parameter space, which makes the final distribution center around the initial value instead of the actual potential center.

For problem 3, the ***model*** function seems to be right. However, I think the likelihood is not calculated correctly in ***metroplis_hastings_2*** and it seems there isn't a random parameter (u) generated to determine whether to accept the sample.

**Comment by gnarayan** [comment]
Good review, @frankfjy - @cspatel2 if you feel like making minor edits per this feedback, that's fine - I'll leave the PR open.

**Comment by gnarayan** [comment]
Actually, I had to revert this because there's a ton of changed files that are now the HW assignment. Could you please fix the PR with only your homework file changed.

**Pull request merged**
